import {rad,deg,fmt,solveTriangle} from './math.mjs';

const field=(key,label,value,min=-1000,max=1000,step='any')=>({key,label,value,min,max,step});
export const explorations=[
 {slug:'right-triangle',title:'Pythagorean calculator',category:'Geometry',icon:'△',description:'Find the hypotenuse or a missing leg, then see the area and both acute angles.',fields:[field('a','Known leg a',6,0.001,10000),field('b','Known leg b / hypotenuse c',8,0.001,10000)],modes:[['hypotenuse','Find the hypotenuse'],['leg','Find a missing leg']],formula:'a² + b² = c²',note:'In missing-leg mode, the second measurement is the hypotenuse c. Lengths use the same arbitrary unit.',lesson:'pythagorean-theorem'},
 {slug:'polygon-explorer',title:'Regular polygon explorer',category:'Geometry',icon:'⬡',description:'Explore the interior angles, diagonals, perimeter, and area of regular polygons.',fields:[field('n','Number of sides',6,3,30,1),field('s','Side length',4,0.001,10000)],formula:'Interior angle = (n − 2) × 180° / n',note:'A regular polygon has equal sides and equal interior angles. The diagram uses a normalized scale.',lesson:'polygon-angles'},
 {slug:'coordinate-geometry',title:'Distance, midpoint & slope',category:'Coordinates',icon:'↗',description:'Move two points and connect the distance formula, midpoint, slope, and line equation.',fields:[field('x1','Point A · x',-3,-10,10),field('y1','Point A · y',-2,-10,10),field('x2','Point B · x',4,-10,10),field('y2','Point B · y',5,-10,10)],formula:'d = √[(x₂ − x₁)² + (y₂ − y₁)²]',note:'Drag either point on the grid, or enter its coordinates. Coincident points have no unique line.',lesson:'distance-and-midpoint'},
 {slug:'circle-sectors',title:'Arc length & sectors',category:'Geometry',icon:'◔',description:'Change a central angle to explore the corresponding arc, chord, and sector area.',fields:[field('r','Radius',5,0.001,10000),field('theta','Central angle (°)',90,0,360,1)],formula:'Arc length = rθ · Sector area = ½r²θ',note:'These formulas use θ in radians. The tool converts the entered degrees automatically. Angles above 180° describe major sectors.',lesson:'arcs-and-sectors'},
 {slug:'angle-converter',title:'Degrees, radians & turns',category:'Trigonometry',icon:'π',description:'Convert angles in either direction and find the coterminal angle and quadrant.',fields:[field('angle','Angle value',90,-100000,100000)],modes:[['degrees','Degrees'],['radians','Radians'],['turns','Turns']],formula:'180° = π radians = ½ turn',note:'For π-based input, choose radians and enter a decimal, or use a preset below. Negative angles rotate clockwise.',lesson:'radians-and-degrees'},
 {slug:'trig-graphs',title:'Sine & cosine graph explorer',category:'Trigonometry',icon:'∿',description:'See amplitude, period, phase shift, and vertical shift change a wave in real time.',fields:[field('a','Amplitude A',1,0,4,0.1),field('b','Frequency factor B',1,0.25,4,0.25),field('h','Phase shift h (radians)',0,-6.2832,6.2832,0.1),field('k','Vertical shift k',0,-3,3,0.1)],modes:[['sin','Sine'],['cos','Cosine']],formula:'y = A sin(B(x − h)) + k',note:'The graph spans −2π to 2π on the x-axis. x and h are measured in radians.',lesson:'trig-graph-transformations'},
 {slug:'transformations',title:'Transformation playground',category:'Coordinates',icon:'⤨',description:'Translate, rotate, reflect, or scale a triangle and compare its coordinates and area.',fields:[field('dx','Horizontal translation',2,-5,5,0.5),field('dy','Vertical translation',1,-5,5,0.5),field('angle','Rotation angle (°)',90,-360,360,15),field('scale','Scale factor',1.5,0.25,3,0.25)],modes:[['translate','Translate'],['rotate','Rotate'],['reflect-x','Reflect over x-axis'],['reflect-y','Reflect over y-axis'],['scale','Scale from origin']],formula:'Rotation: (x, y) → (x cos θ − y sin θ, x sin θ + y cos θ)',note:'The original triangle is A(−2, −1), B(2, −1), C(0, 2). Rotations and dilations are centered at the origin.',lesson:'transformations'},
 {slug:'triangle-playground',title:'Triangle discovery sandbox',category:'Geometry',icon:'∠',description:'Drag three vertices to discover triangle types, area, perimeter, and the centroid.',fields:[field('ax','A · x',-4,-9,9),field('ay','A · y',-3,-9,9),field('bx','B · x',4,-9,9),field('by','B · y',-3,-9,9),field('cx','C · x',0,-9,9),field('cy','C · y',4,-9,9)],formula:'Area = ½ |x₁(y₂ − y₃) + x₂(y₃ − y₁) + x₃(y₁ − y₂)|',note:'Drag a vertex or enter coordinates. Use the challenges to discover how shapes behave.',lesson:'triangle-centers'},
];
export function validateFields(tool,values){for(const f of tool.fields){const v=values[f.key];if(!Number.isFinite(v)||v<f.min||v>f.max)throw Error(`${f.label}: enter a value from ${f.min} to ${f.max}.`);}if(tool.slug==='polygon-explorer'&&!Number.isInteger(values.n))throw Error('The number of sides must be a whole number.');}
export const polygonArea=pts=>Math.abs(pts.reduce((s,p,i)=>{const q=pts[(i+1)%pts.length];return s+p[0]*q[1]-p[1]*q[0]},0))/2;
export function transformPoint([x,y],mode,v){switch(mode){case'translate':return[x+v.dx,y+v.dy];case'rotate':return[x*Math.cos(rad(v.angle))-y*Math.sin(rad(v.angle)),x*Math.sin(rad(v.angle))+y*Math.cos(rad(v.angle))];case'reflect-x':return[x,-y];case'reflect-y':return[-x,y];case'scale':return[x*v.scale,y*v.scale];default:throw Error('Choose a transformation.');}}
export function explore(slug,v,mode){const tool=explorations.find(t=>t.slug===slug);if(!tool)throw Error('Unknown tool.');validateFields(tool,v);const metrics=[],steps=[];let model={};const m=(label,value)=>metrics.push({label,value});
 if(slug==='right-triangle'){const a=v.a;let b,c;if(mode==='leg'){c=v.b;if(c<=a)throw Error('The hypotenuse must be longer than the known leg.');b=Math.sqrt((c-a)*(c+a));}else{b=v.b;c=Math.hypot(a,b);}const A=deg(Math.atan2(a,b)),B=90-A;m('Leg a',fmt(a));m('Leg b',fmt(b));m('Hypotenuse c',fmt(c));m('Area',fmt(a*b/2)+' units²');m('Angle A',fmt(A)+'°');m('Angle B',fmt(B)+'°');steps.push(mode==='leg'?`b = √(c² − a²) = √(${fmt(c*c)} − ${fmt(a*a)}) = ${fmt(b)}`:`c = √(a² + b²) = √(${fmt(a*a)} + ${fmt(b*b)}) = ${fmt(c)}`,`Area = ab / 2 = ${fmt(a*b/2)} square units.`,`Angle A = arctan(a / b) = ${fmt(A)}°. Angle B = 90° − A = ${fmt(B)}°.`);model={a,b,c};}
 if(slug==='polygon-explorer'){const {n,s}=v;const interior=(n-2)*180/n,perimeter=n*s,apothem=s/(2*Math.tan(Math.PI/n)),area=perimeter*apothem/2;m('Interior angle',fmt(interior)+'°');m('Exterior angle',fmt(360/n)+'°');m('Angle sum',fmt((n-2)*180)+'°');m('Diagonals',String(n*(n-3)/2));m('Perimeter',fmt(perimeter));m('Area',fmt(area)+' units²');steps.push(`Split the polygon into ${n-2} triangles: interior-angle sum = (${n} − 2) × 180° = ${fmt((n-2)*180)}°.`,`Divide the sum by ${n} for each equal interior angle: ${fmt(interior)}°.`,`Apothem = s / (2 tan(π/n)) = ${fmt(apothem)}. Area = perimeter × apothem / 2 = ${fmt(area)}.`);model={n,s,apothem};}
 if(slug==='coordinate-geometry'){const {x1,y1,x2,y2}=v,dx=x2-x1,dy=y2-y1,distance=Math.hypot(dx,dy),mid=[(x1+x2)/2,(y1+y2)/2];const coincident=distance<1e-10,vertical=Math.abs(dx)<1e-10,slope=coincident||vertical?null:dy/dx;const intercept=slope===null?null:y1-slope*x1;const equation=coincident?'No unique line':vertical?`x = ${fmt(x1)}`:`y = ${fmt(slope)}x ${intercept<0?'−':'+'} ${fmt(Math.abs(intercept))}`;m('Distance',fmt(distance));m('Midpoint',`(${fmt(mid[0])}, ${fmt(mid[1])})`);m('Slope',slope===null?'undefined':fmt(slope));m('Line equation',equation);steps.push(`Δx = ${fmt(dx)}, Δy = ${fmt(dy)}. Distance = √(Δx² + Δy²) = ${fmt(distance)}.`,`Average each coordinate to get the midpoint: (${fmt(mid[0])}, ${fmt(mid[1])}).`,coincident?'Both points coincide, so they do not determine a unique line.':vertical?'Δx = 0, so the line is vertical and the slope is undefined.':`Slope = Δy / Δx = ${fmt(slope)}. Substitute a point into y = mx + b to find b = ${fmt(intercept)}.`);model={points:[[x1,y1],[x2,y2]],mid,slope,dx,dy,distance};}
 if(slug==='circle-sectors'){const {r,theta}=v,t=rad(theta),arc=r*t,area=r*r*t/2,chord=2*r*Math.sin(t/2);m('Arc length',fmt(arc));m('Sector area',fmt(area)+' units²');m('Chord length',fmt(chord));m('Fraction of circle',fmt(theta/360*100)+'%');steps.push(`θ = ${theta}° × π / 180 = ${fmt(t,5)} radians.`,`Arc length = rθ = ${fmt(arc)} units. Sector area = r²θ / 2 = ${fmt(area)} square units.`,`The straight chord has length 2r sin(θ/2) = ${fmt(chord)} units.`);model={r,theta};}
 if(slug==='angle-converter'){const degrees=mode==='radians'?deg(v.angle):mode==='turns'?v.angle*360:v.angle;const radians=rad(degrees),turns=degrees/360,normalized=((degrees%360)+360)%360;const axis=Math.abs(normalized/90-Math.round(normalized/90))<1e-9;m('Degrees',fmt(degrees,5)+'°');m('Radians',fmt(radians,5));m('Turns',fmt(turns,5));m('Coterminal angle',fmt(normalized,5)+'°');m('Position',axis?'On an axis':'Quadrant '+(Math.floor(normalized/90)+1));steps.push(`Degrees = ${fmt(degrees,5)}°. Multiply by π / 180 to get ${fmt(radians,5)} radians.`,`Divide degrees by 360 to get ${fmt(turns,5)} turns.`,`Adding or subtracting full turns gives the equivalent angle ${fmt(normalized,5)}° in [0°, 360°).`);model={degrees,normalized};}
 if(slug==='trig-graphs'){const {a,b,h,k}=v,period=2*Math.PI/b;m('Amplitude',fmt(a));m('Period',a===0?'Not unique':fmt(period)+' rad');m('Phase shift',fmt(h)+' rad');m('Midline',`y = ${fmt(k)}`);m('Range',`[${fmt(k-a)}, ${fmt(k+a)}]`);steps.push(`y = ${fmt(a)} ${mode}(${fmt(b)}(x − (${fmt(h)}))) + (${fmt(k)}).`,`Period = 2π / B = ${fmt(period)} radians. When A = 0, the graph is constant and has no unique fundamental period.`,`Positive h moves the wave right; k moves its midline vertically. The minimum is ${fmt(k-a)} and the maximum is ${fmt(k+a)}.`);model={a,b,h,k,fn:mode};}
 if(slug==='transformations'){const before=[[-2,-1],[2,-1],[0,2]],after=before.map(p=>transformPoint(p,mode,v)),area=polygonArea(after);after.forEach((p,i)=>m(`${'ABC'[i]}′`,`(${fmt(p[0])}, ${fmt(p[1])})`));m('Original area','6 units²');m('New area',fmt(area)+' units²');m('Area factor',fmt(area/6)+'×');steps.push(mode==='translate'?`Add (${v.dx}, ${v.dy}) to each point.`:mode==='rotate'?`Rotate each point ${v.angle}° counterclockwise about the origin.`:mode==='scale'?`Multiply both coordinates by ${v.scale}.`:mode==='reflect-x'?'Keep x and reverse the sign of y.':'Reverse the sign of x and keep y.',mode==='scale'?`Lengths scale by ${v.scale}; area scales by ${fmt(v.scale*v.scale)}.`:'This transformation preserves lengths, angles, and area.');model={before,after};}
 if(slug==='triangle-playground'){const pts=[[v.ax,v.ay],[v.bx,v.by],[v.cx,v.cy]],dist=(p,q)=>Math.hypot(p[0]-q[0],p[1]-q[1]),a=dist(pts[1],pts[2]),b=dist(pts[0],pts[2]),c=dist(pts[0],pts[1]),area=polygonArea(pts),center=[(v.ax+v.bx+v.cx)/3,(v.ay+v.by+v.cy)/3];if(area<1e-7)throw Error('The vertices are on a line or overlap. Move one point to make a triangle.');const t=solveTriangle('sss',[a,b,c])[0],right=[t.A,t.B,t.C].some(n=>Math.abs(n-90)<0.1);const equal=(u,w)=>Math.abs(u-w)<0.001*Math.max(u,w);const type=equal(a,b)&&equal(b,c)?'Equilateral':equal(a,b)||equal(b,c)||equal(a,c)?'Isosceles':'Scalene';m('Side type',type);m('Angle type',right?'Right':Math.max(t.A,t.B,t.C)>90?'Obtuse':'Acute');m('Area',fmt(area)+' units²');m('Perimeter',fmt(a+b+c));m('Angles A · B · C',`${fmt(t.A,1)}° · ${fmt(t.B,1)}° · ${fmt(t.C,1)}°`);m('Centroid',`(${fmt(center[0])}, ${fmt(center[1])})`);steps.push(`Opposite sides: a = ${fmt(a)}, b = ${fmt(b)}, c = ${fmt(c)}.`,`The coordinate (shoelace) formula gives area ${fmt(area)}. The angle sum is 180°.`,`Average the three x-coordinates and three y-coordinates to locate the centroid. It divides each median in a 2:1 ratio.`);model={points:pts,center,area,type,right};}
 return {metrics,steps,model};
}
